### ISSUE TITLE
Pathfinding problems with multiple lane roads

### ISSUE THREAD

**Issue by LordSmeghead** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#192]
I'm finding a problem when using any multiple lane road, almost all cars are refusing to change lanes once they enter the multiple lane section of road. A very small minority are able to change lanes and generally act normally but the majority of vehicles remain stuck on their lanes unable to change lanes to go in a different direction that would get to their destination quicker. This means that I'm ending up with traffic taking extremely circuitous routes or going onto roads not equipped to deal with that level of traffic. I've got a few examples of whats going on in some screenshots below with traffic entering the highways at the highlighted sections (I'm using left hand traffic in my city);

![20180714171822_1](https://user-images.githubusercontent.com/41238674/42726577-a8069d90-878e-11e8-98e8-66929176a228.jpg)
![20180714171838_1](https://user-images.githubusercontent.com/41238674/42726578-a82289e2-878e-11e8-9681-3165cb34595d.jpg)
![20180714171852_1](https://user-images.githubusercontent.com/41238674/42726579-a8408118-878e-11e8-8fc5-8cb22f7fd269.jpg)
![20180714171918_1](https://user-images.githubusercontent.com/41238674/42726580-a86c3c54-878e-11e8-9688-1d8a88df1ced.jpg)

All of these occur when lane connections have been used at one or both of the junctions. As can be seen traffic entering the highways is forced to follow the lane they have entered on and are unable to change lanes and take a faster route to their destination. This is also happening on many of the multi lane city streets as well (I haven't screenshot those as it's harder to see what's going on). Maximising advanced lane selection does not solve the issue, instead cars will spread out and use all of the lanes before all attempting to get back into the same lane as previously. This has all meant that my traffic flow has dropped to about 65-70% rather than the usual 80-85%.

**Comment by VictorPhilipp** [comment]
Could you please provide your savegame?

**Comment by SquareBeard** [comment]
Probably related to #191

**Comment by Videonauth** [comment]
So O.k. I had a look at my game and some of the path finds are really weird. Like going from one district to to a neighboring one, but the trucks take a route which is going through another district far away from the ideal route. I would provide my savegame but you would need about 40 GB disk space for assets and at least 90+ GB ram to load it in its current state.

**Comment by VictorPhilipp** [comment]
I fixed an error in the cost calculation of the Vehicle AI (see issue #191). If this issue is caused by the same problem then this should also be fixed now.

**Comment by Videonauth** [comment]
If this is in the 1.10.10 version its still present on my game I'm using this version actually. Or did I miss an update?

**Comment by Videonauth** [comment]
As far I can see in my savegame, the pathfinding works as it should.

**Comment by LordSmeghead** [comment]
Yup the error was fixed alongside #191, it all works as it should, thank you very much.
